"""Pydantic models for E*Trade API responses."""

from etrade_client.models.accounts import (
    Account,
    AccountBalance,
    AccountListResponse,
    AccountStatus,
    AccountType,
    BalanceResponse,
    # Portfolio quote models
    CompleteQuote,
    # Portfolio position models
    CompleteViewPosition,
    FundamentalQuote,
    FundamentalViewPosition,
    PerformanceQuote,
    PerformanceViewPosition,
    PortfolioPosition,
    PortfolioPositionBase,
    PortfolioResponse,
    PositionType,
    QuickQuote,
    QuickViewPosition,
)
from etrade_client.models.alerts import (
    Alert,
    AlertCategory,
    AlertDetail,
    AlertDetailResponse,
    AlertListResponse,
    AlertStatus,
    DeleteAlertsResponse,
)
from etrade_client.models.auth import AccessToken, RequestToken
from etrade_client.models.market import (
    # Quote detail models by detail_flag
    AllQuoteDetail,
    AllQuoteDetails,  # Backwards compatibility alias
    ExtendedHourQuoteDetail,
    FundamentalQuoteDetail,
    IntradayQuoteDetail,
    # Option chain models
    OptionChain,
    OptionExpireDate,
    OptionExpiryType,
    OptionsQuoteDetail,
    OptionType,
    # Quote wrapper and response
    Quote,
    QuoteResponse,
    QuoteStatus,
    Week52QuoteDetail,
)
from etrade_client.models.orders import (
    CallPut,
    MarketSession,
    Order,
    OrderAction,
    OrderDetail,
    OrderListResponse,
    OrderPreview,
    OrderPreviewResponse,
    OrderStatus,
    OrderTerm,
    OrderType,
    PlaceOrderResponse,
    SecurityType,
)
from etrade_client.models.transactions import (
    # Transaction subclasses
    BillPaymentTransaction,
    BoughtTransaction,
    Brokerage,
    BrokerageWithoutProduct,
    BrokerageWithProduct,
    CashInLieuTransaction,
    DividendTransaction,
    ExchangeDeliveredOutTransaction,
    ExchangeReceivedInTransaction,
    FeeTransaction,
    FundsReceivedTransaction,
    GenericTransaction,
    InterestIncomeTransaction,
    MarginInterestTransaction,
    PosTransaction,
    Product,
    ServiceFeeTransaction,
    SoldTransaction,
    # Response model
    Transaction,
    # Base classes
    TransactionBase,
    TransactionListResponse,
    # Enum
    TransactionType,
    TransferTransaction,
)

__all__ = [
    "AccessToken",
    "Account",
    "AccountBalance",
    "AccountListResponse",
    "AccountStatus",
    "AccountType",
    "Alert",
    "AlertCategory",
    "AlertDetail",
    "AlertDetailResponse",
    "AlertListResponse",
    "AlertStatus",
    "AllQuoteDetail",
    "AllQuoteDetails",
    "BalanceResponse",
    "BillPaymentTransaction",
    "BoughtTransaction",
    "Brokerage",
    "BrokerageWithProduct",
    "BrokerageWithoutProduct",
    "CallPut",
    "CashInLieuTransaction",
    "CompleteQuote",
    "CompleteViewPosition",
    "DeleteAlertsResponse",
    "DividendTransaction",
    "ExchangeDeliveredOutTransaction",
    "ExchangeReceivedInTransaction",
    "ExtendedHourQuoteDetail",
    "FeeTransaction",
    "FundamentalQuote",
    "FundamentalQuoteDetail",
    "FundamentalViewPosition",
    "FundsReceivedTransaction",
    "GenericTransaction",
    "InterestIncomeTransaction",
    "IntradayQuoteDetail",
    "MarginInterestTransaction",
    "MarketSession",
    "OptionChain",
    "OptionExpireDate",
    "OptionExpiryType",
    "OptionType",
    "OptionsQuoteDetail",
    "Order",
    "OrderAction",
    "OrderDetail",
    "OrderListResponse",
    "OrderPreview",
    "OrderPreviewResponse",
    "OrderStatus",
    "OrderTerm",
    "OrderType",
    "PerformanceQuote",
    "PerformanceViewPosition",
    "PlaceOrderResponse",
    "PortfolioPosition",
    "PortfolioPositionBase",
    "PortfolioResponse",
    "PosTransaction",
    "PositionType",
    "Product",
    "QuickQuote",
    "QuickViewPosition",
    "Quote",
    "QuoteResponse",
    "QuoteStatus",
    "RequestToken",
    "SecurityType",
    "ServiceFeeTransaction",
    "SoldTransaction",
    "Transaction",
    "TransactionBase",
    "TransactionListResponse",
    "TransactionType",
    "TransferTransaction",
    "Week52QuoteDetail",
]
